
import os
import psycopg2
import psycopg2.extras
from prettytable import PrettyTable
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py


def query():
    load_dotenv()

    user = os.getenv('DB_USER', 'postgres')
    password = os.getenv('DB_PASSWORD', '1234')
    dbname = os.getenv('DB_NAME', 'sales')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor, host='127.0.0.1', port='5432')
    cur = conn.cursor()
    
    # For EMF queries, we need the whole sales table
    if not 'group-by-sql/1.sql'.endswith('.sql'):
        cur.execute("SELECT * FROM sales")

    _global = []
    
    # Execute raw SQL query
    sql_query = """
SELECT 
    main.cust,
    ny.sum_quant AS sum_1_quant,
    ny.avg_quant AS avg_1_quant,
    ny.max_quant AS max_1_quant,
    ny.min_quant AS min_1_quant,
    ny.count_quant AS count_1_quant,
    ct.sum_quant AS sum_2_quant,
    ct.avg_quant AS avg_2_quant,
    ct.max_quant AS max_2_quant,
    ct.min_quant AS min_2_quant,
    ct.count_quant AS count_2_quant
FROM 
    (SELECT DISTINCT cust FROM sales) main
LEFT JOIN 
    (SELECT 
        cust,
        SUM(quant) AS sum_quant,
        AVG(quant) AS avg_quant,
        MAX(quant) AS max_quant,
        MIN(quant) AS min_quant,
        COUNT(quant) AS count_quant
     FROM sales
     WHERE state = 'NY'
     GROUP BY cust) ny ON main.cust = ny.cust
LEFT JOIN 
    (SELECT 
        cust,
        SUM(quant) AS sum_quant,
        AVG(quant) AS avg_quant,
        MAX(quant) AS max_quant,
        MIN(quant) AS min_quant,
        COUNT(quant) AS count_quant
     FROM sales
     WHERE state = 'CT'
     GROUP BY cust) ct ON main.cust = ct.cust

    """
    
    # Use a generator to efficiently process results
    def result_generator():
        cur.execute(sql_query)
        while True:
            rows = cur.fetchmany(100)  # Fetch in batches for efficiency
            if not rows:
                break
            for row in rows:
                yield row
    
    # Create PrettyTable for output
    table = PrettyTable()
    
    # Get column names from cursor description
    if cur.description:
        table.field_names = [desc[0] for desc in cur.description]
    
    # Add rows to table
    for row in result_generator():
        if isinstance(row, dict):
            table.add_row([row.get(field) for field in table.field_names])
        else:
            table.add_row(row)
    
    return table


if "__main__" == __name__:
    print(query())
    