
import os
import psycopg2
import psycopg2.extras
from prettytable import PrettyTable
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py


def query():
    load_dotenv()

    user = os.getenv('DB_USER', 'postgres')
    password = os.getenv('DB_PASSWORD', '1234')
    dbname = os.getenv('DB_NAME', 'sales')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor, host='127.0.0.1', port='5432')
    cur = conn.cursor()
    
    # For EMF queries, we need the whole sales table
    if not 'group-by-sql/2.sql'.endswith('.sql'):
        cur.execute("SELECT * FROM sales")

    _global = []
    
    # Execute raw SQL query
    sql_query = """
SELECT 
    main.prod,
    main.month,
    before_month.avg_quant AS avg_1_quant,
    after_month.avg_quant AS avg_2_quant
FROM 
    (SELECT DISTINCT prod, month FROM sales) main
LEFT JOIN 
    (SELECT 
        s1.prod,
        s1.month AS main_month,
        AVG(s2.quant) AS avg_quant
     FROM 
        (SELECT DISTINCT prod, month FROM sales) s1
     JOIN 
        sales s2 ON s1.prod = s2.prod AND s2.month < s1.month
     GROUP BY 
        s1.prod, s1.month) before_month 
    ON main.prod = before_month.prod AND main.month = before_month.main_month
LEFT JOIN 
    (SELECT 
        s1.prod,
        s1.month AS main_month,
        AVG(s2.quant) AS avg_quant
     FROM 
        (SELECT DISTINCT prod, month FROM sales) s1
     JOIN 
        sales s2 ON s1.prod = s2.prod AND s2.month > s1.month
     GROUP BY 
        s1.prod, s1.month) after_month 
    ON main.prod = after_month.prod AND main.month = after_month.main_month

    """
    
    # Use a generator to efficiently process results
    def result_generator():
        cur.execute(sql_query)
        while True:
            rows = cur.fetchmany(100)  # Fetch in batches for efficiency
            if not rows:
                break
            for row in rows:
                yield row
    
    # Create PrettyTable for output
    table = PrettyTable()
    
    # Get column names from cursor description
    if cur.description:
        table.field_names = [desc[0] for desc in cur.description]
    
    # Add rows to table
    for row in result_generator():
        if isinstance(row, dict):
            table.add_row([row.get(field) for field in table.field_names])
        else:
            table.add_row(row)
    
    return table


if "__main__" == __name__:
    print(query())
    